version: "2.7"
services:
  mysql:
    image: mysql:8.0-debian
    environment:
      - MYSQL_ROOT_PASSWORD=Hoang2002
      - MYSQL_DATABASE=doctoranywhere
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    expose:
      - "3306"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Hoang2002
      - MYSQL_DATABASE=doctoranywhere
    depends_on:
      mysql:
        condition: service_healthy
